name: GitHub Actions Demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Outout the name of the event triggered this workflow
      - run: |
          echo "The job was triggered by event: ${{github.event_name}}"

      - name: Checkout repo
      - uses: action/checkout@V4

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
          
  
    
